memorizer/views/admin.py
import json

from flask import Blueprint, flash, render_template, request

from memorizer import importer, models
from memorizer.forms import AlternativeForm, CourseForm, ExamForm, QuestionForm
from memorizer.user import login_required

admin = Blueprint('admin', __name__)


@admin.route('/')
@login_required
def index():
    return render_template('admin/admin.html')


@admin.route('/courses', methods=['GET', 'POST'])
@login_required
def courses():
    # JSON question post
    if request.method == 'POST':
        exam_json = request.form.get('json')
        if exam_json:
            try:
                questions = json.loads(exam_json)
                importer.import_exam(questions)
                flash('Alle spørsmålene ble importert', 'success')
            except json.decoder.JSONDecodeError:
                flash('Ugyldig JSON', 'error')
            except importer.ValidationError as e:
                flash(e, 'error')
        else:
            flash('Tom JSON', 'error')

    context = dict(courses=models.Course.query.all())
    form = CourseForm()
    context['form'] = form
    return render_template('admin/courses.html', **context)


@admin.route('/course/<string:course_id>')
@login_required
def course(course_id):
    course = models.Course.query.filter_by(id=course_id).first_or_404()
    form = CourseForm(obj=course)
    exam = models.Exam(course_id=course.id)
    exam_form = ExamForm(obj=exam)
    context = dict(course=course, form=form, exam_form=exam_form)
    return render_template('admin/course.html', **context)


@admin.route('/course/<string:course_id>/<string:exam_id>')
@login_required
def exam(course_id, exam_id):
    course = models.Course.query.filter_by(id=course_id).first_or_404()
    exam = models.Exam.query.filter_by(course=course, id=exam_id).first_or_404()
    form = ExamForm(obj=exam)
    question = models.Question(exam_id=exam.id)
    question_form = QuestionForm(obj=question)
    context = dict(exam=exam, course=course, form=form, question_form=question_form)
    return render_template('admin/exam.html', **context)


@admin.route('/question/<int:question_id>')
@login_required
def question(question_id):
    question = question = models.Question.query.filter_by(id=question_id).first_or_404()
    query = models.Question.query.filter_by(exam=question.exam)
    prev_question = query.filter(models.Question.id < question_id).order_by('-id').first()
    next_question = query.filter(models.Question.id > question_id).first()
    form = QuestionForm(obj=question)
    alt = models.Alternative(question_id=question.id)
    alt_form = AlternativeForm(obj=alt)
    context = dict(
        question=question, form=form, alt_form=alt_form,
        next_question=next_question, prev_question=prev_question
    )
    return render_template('admin/question.html', **context)


@admin.route('/question/<int:question_id>/<int:alternative_id>')
@login_required
def alternative(question_id, alternative_id):
    question = models.Question.query.filter_by(id=question_id).first_or_404()
    alternative = models.Alternative.query.filter_by(id=alternative_id).first_or_404()
    form = AlternativeForm(obj=alternative)
    context = dict(form=form, question=question, alternative=alternative)
    return render_template('admin/alternative.html', **context)

memorizer/views/quiz.py
import random

from flask import Blueprint, abort, flash, redirect, render_template, request, session, url_for

from memorizer import forms, models, utils
from memorizer.user import get_user
from memorizer.views import TemplateMethodView

quiz = Blueprint('quiz', __name__)


@quiz.route('/')
def main():
    context = {'courses': models.Course.query.all()}
    return render_template('quiz/courses.html', **context)


class Register(TemplateMethodView):
    template = 'quiz/register.html'
    methods = ['GET', 'POST']

    def context(self, *args, **kwargs):
        context = super().context(*args, **kwargs)
        context['form'] = self.form
        return context

    def get(self):
        user = get_user()
        if user.registered:
            flash('Du er allerede logget inn', 'error')
            return redirect(url_for('quiz.main'))
        self.form = forms.RegisterForm()

    def post(self):
        response = self.get()
        if response:
            return response
        form = forms.RegisterForm(request.form)
        if form.validate():
            self.save_user(form)
            flash('Registrering fullført', 'success')
            return redirect(url_for('quiz.main'))
        self.form = form

    def save_user(self, form):
        user = get_user()
        user.name = form.name.data
        user.username = form.username.data
        user.password = form.password.data
        user.registered = True
        models.db.session.add(user)
        models.db.session.commit()


quiz.add_url_rule('/register/', view_func=Register.as_view('register'))


@quiz.route('/login/', methods=['GET', 'POST'])
def login():
    user = get_user()
    if user.registered:
        flash('Du er allerede logget inn', 'error')
        return redirect(url_for('quiz.main'))
    if request.method == 'POST':
        form = forms.LoginForm(request.form)
        if form.validate():
            # Login
            user = models.User.query.filter_by(username=form.username.data).first()
            if user and user.password == form.password.data:
                session['user'] = user.id
                return redirect(url_for('quiz.main'))
    else:
        form = forms.LoginForm()
    context = dict(form=form)
    return render_template('quiz/login.html', **context)


@quiz.route('/logout/')
def logout():
    if 'user' in session:
        del session['user']
    return redirect(url_for('quiz.main'))


@quiz.route('/tips/')
def tips():
    return render_template('quiz/tips.html')


@quiz.route('/reset/<string:course>/')
def reset_stats_course(course):
    """Reset stats for a course"""
    # Check if course exists
    course = models.Course.query.filter_by(code=course).first_or_404()
    stats_query = models.Stats.course(get_user(), course.code).with_entities(models.Stats.id).subquery()
    models.Stats.query.filter(models.Stats.id.in_(stats_query)).\
        update({models.Stats.reset: True}, synchronize_session=False)
    models.db.session.commit()
    return redirect(url_for('quiz.course', course=course.code))


@quiz.route('/reset/<string:course>/<string:exam>/')
def reset_stats_exam(course, exam):
    """Reset stats for a course"""
    course = models.Course.query.filter_by(code=course).first_or_404()
    exam = models.Exam.query.filter_by(course=course, name=exam).first_or_404()
    stats_query = models.Stats.exam(get_user(), course.code, exam.name).with_entities(models.Stats.id).subquery()
    models.Stats.query.filter(models.Stats.id.in_(stats_query)).\
        update({models.Stats.reset: True}, synchronize_session=False)
    models.db.session.commit()
    return redirect(url_for('quiz.exam', course=course.code, exam=exam.name))


@quiz.route('/<string:course>/')
@quiz.route('/<string:course>/all/0')
def course(course):
    """Redirects to a random question for a chosen course"""
    models.Course.query.filter_by(code=course).first_or_404()
    return redirect(url_for(
        'quiz.question_course', course_code=course, id=utils.random_id(course=course))
    )


@quiz.route('/<string:course>/<string:exam>/')
@quiz.route('/<string:course>/<string:exam>/0')
def exam(course, exam):
    """Redirects to the first question for a chosen exam"""
    course_m = models.Course.query.filter_by(code=course).first_or_404()
    exam_m = models.Exam.query.filter_by(course=course_m, name=exam).first_or_404()
    return redirect(url_for('quiz.question_exam', course_code=course, exam_name=exam_m.name, id=1))


class QuestionMixin:
    template = 'quiz/question.html'
    methods = ['GET', 'POST']

    def context(self, *args, **kwargs):
        context = super().context(*args, **kwargs)
        context.update({
            'id': self.number,
            'prev': self.next(),
            'next': self.previous(),
            'question': self.question,
            'answered': getattr(self, 'answered', None),
            'success': getattr(self, 'success', None),
            'stats': self.model.stats()
        })
        return context

    def next(self):
        if self.number > 1:
            return self.number - 1
        else:
            return self.model.question_count

    def previous(self):
        if self.number < self.model.question_count:
            return self.number + 1
        else:
            return 1

    def get(self, number, *args, **kwargs):
        if self.model.question_count == 0:
            abort(404)
        self.number = number
        self.question = self.model.question(number).first_or_404()
        self.sort_exams()
        self.scramble_alternatives()

    def post(self, *args, **kwargs):
        self.get(*args, **kwargs)
        answer = request.form.get('answer')
        if answer:
            self.answered = True
            if self.question.multiple:
                self.success = self.alternatives_correct()
            else:
                bool_answer = answer.lower() == 'true'
                self.success = self.question.correct == bool_answer
            user = get_user()
            # Checking if question has already been answered
            if not models.Stats.answered(user, self.question):
                self.save_answer(user, self.success)
            elif self.success:
                flash('Du har allerede svart på dette spørsmålet så du får ikke noe poeng. :-)', 'info')
        else:
            flash('Blankt svar', 'error')
        # Preserving order on submit
        ordering = request.form.get('order')
        if ordering:
            self.reorder_alternatives(ordering)

    def sort_exams(self):
        self.question.course.exams.sort(key=utils.sort_exam, reverse=True)

    def scramble_alternatives(self):
        dict_alt = {alt.id: alt for alt in self.question.alternatives}
        indexes = list(dict_alt.keys())
        random.shuffle(indexes)
        self.question.alternatives = [dict_alt[index] for index in indexes]

    def reorder_alternatives(self, ordering):
        dict_alt = {alt.id: alt for alt in self.question.alternatives}
        indexes = map(int, ordering.split(','))
        self.question.alternatives = [dict_alt[index] for index in indexes]

    def alternatives_correct(self):
        try:
            answers = set(map(int, request.form.getlist('answer')))
        except ValueError:
            return False
        correct_alternatives = models.Alternative.query.filter_by(question=self.question, correct=True)
        correct_answers = {alt.id for alt in correct_alternatives}
        if self.question.exam.multiple_correct:
            return correct_answers == answers
        else:
            return answers <= correct_answers

    def save_answer(self, user, success):
        stat = models.Stats(user, self.question, success)
        models.db.session.add(stat)
        models.db.session.commit()


class CourseQuestion(QuestionMixin, TemplateMethodView):
    def get(self, course_code, id, *args, **kwargs):
        self.model = models.Course.query.filter_by(code=course_code).first_or_404()
        return super().get(id, course_code, *args, **kwargs)

    def context(self, *args, **kwargs):
        context = super().context(*args, **kwargs)
        reset_url = url_for('quiz.reset_stats_course', course=self.model.code)
        random_question = utils.random_id(id=id, course=self.model.code)

        context.update({
            'exam_name': 'all',
            'reset_url': reset_url,
            'random': random_question
        })
        return context


quiz.add_url_rule(
    '/<string:course_code>/all/<int:id>',
    view_func=CourseQuestion.as_view('question_course')
)


class ExamQuestion(QuestionMixin, TemplateMethodView):
    def get(self, course_code, exam_name, id, *args, **kwargs):
        course = models.Course.query.filter_by(code=course_code).first_or_404()
        self.model = models.Exam.query.filter_by(course=course, name=exam_name, hidden=False).first_or_404()
        return super().get(id, course_code, exam_name, *args, **kwargs)

    def context(self, *args, **kwargs):
        context = super().context(*args, **kwargs)
        random_question = utils.random_id(id=id, course=self.model.course.code)
        reset_url = url_for('quiz.reset_stats_exam', course=self.model.course.code, exam=self.model.name)

        context.update({
            'exam_name': self.model.name,
            'reset_url': reset_url,
            'random': random_question
        })
        return context


quiz.add_url_rule(
    '/<string:course_code>/<string:exam_name>/<int:id>',
    view_func=ExamQuestion.as_view('question_exam')
)

memorizer/templates/quiz/courses.html
{% extends "quiz/quiz.html" %}
{% block content %}
<h1>Emner</h1>
<input type="text" id="search_courses" placeholder="Søk..." autofocus>
<ul class="courses">
{% for course in courses %}
    <li data-text="{{ course.code }} {{ course.name }}">
        <a href="{{ url_for('quiz.course', course=course.code) }}">
            <div class="code">{{ course.code }}</div>
            <div class="count">{{ course.question_count }} <small>spørsmål</small></div>
            <div class="name">{{ course.name }}</div>
        </a>
    </li>
{% endfor %}
</ul>
{% endblock %}

{% block js %}
{{ super () }}
<script>
    new CoursesFilter(document.getElementById('search_courses'), document.querySelector('ul.courses'));
</script>
{% endblock %}

memorizer/templates/quiz/login.html
{% from "admin/_formhelpers.html" import render_form %}
{% extends "admin/admin.html" %}

{% block content %}
<h1>Logg inn</h1>

{{ render_form(form, submit_text="Logg inn") }}

<a class="admin-register" href="{{ url_for('quiz.register') }}">Eller registrer deg</a>
{% endblock %}

memorizer/templates/quiz/question.html
{% extends "quiz/quiz.html" %}
{% block title %}#{{ id }} - {{ question.course.code }} {{ question.exam.name }}{% endblock %}

{% macro navlink(id, name, text) %}
    <a href="{{ url_for('quiz.question_exam', course_code=question.course.code, exam_name=exam_name, id=id) }}" id="{{ name }}">{{ text }}</a>
{% endmacro %}

{% block menu %}
<li><a href="{{ url_for('quiz.main') }}"><i class="fa fa-list fa-fw"></i>&nbsp; Emner</a></li>
<ul>
    <li {% if exam_name == 'all' %}class="active"{% endif %}>
        <a href="{{ url_for('quiz.course', course=question.course.code) }}">
            <i class="fa fa-book fa-fw"></i>&nbsp; {{ question.course.code }}
        </a>
    </li>
    <ul>
    {% for exam in question.course.exams %}
        {% if not exam.hidden %}
        <li {% if exam_name == exam.name %}class="active"{% endif %}>
            <a href="{{ url_for('quiz.exam', course=question.course.code, exam=exam) }}">
                <i class="fa fa-file-text fa-fw"></i>&nbsp; {{ exam }}
            </a>
        </li>
        {% endif %}
    {% endfor %}
    </ul>
</ul>
{% endblock %}

{% block content %}
<div class="question-container">
<h2>{{ question.course.name }} - <span class="question-exam">{{ question.exam }}</span></h2>
{% if question is defined %}
<div class="question">
    <h3>Spørsmål #{{ id }}</h3>
    {% if question.image %}
    <div class="image">
        {% if question.image.startswith('http://') %}
        <img src="{{ question.image }}">
        {% else %}
        <img src="{{ url_for('static', filename='img/' + question.course.code + '/' + question.image) }}">
        {% endif %}
    </div>
    {% endif %}
    <h4>{{ question.text }}</h4>
    <form method="post">
        {% if question.multiple %}
        <input type="hidden" name="order" value="{{ question.choices|join(',', attribute='id') }}">
        {% for alternative in question.choices %}
        <div class="checkbox {% if (alternative.id)|string() in request.form.getlist('answer') %}{{ 'success' if alternative.correct else 'error' }}{% endif %}">
            <label>
                <input type="{% if question.exam.multiple_correct %}checkbox{% else %}radio{% endif %}" name="answer" value="{{ alternative.id }}">
                {% if success is not none %}
                    <i class="fa {{ 'fa-check' if alternative.correct else 'fa-times' }} fa-fw"></i>
                {% endif %}
                {{ alternative }}
            </label>
        </div>
        {% endfor %}
        {% else %}
        {% for bool_val, val, label in [(True, "true", "Ja"), (False, "false", "Nei")] %}
        <div class="radio {% if val == request.form.answer %}{{ 'success' if success else 'error' }}{% endif %}">
            <label>
                <input type="radio" name="answer" value="{{ val }}">
                {% if success is not none %}
                    <i class="fa {{ 'fa-check' if  question.correct == bool_val else 'fa-times' }} fa-fw"></i>
                {% endif %}
                {{ label }}
            </label>
        </div>
        {% endfor %}
        {% endif %}
        <button type="submit">Svar</button>
    </form>
    {% if answered and question.reason %}
    <div class="alert reason">
        <b>Forklaring</b>:
        {{ question.reason }}
    </div>
    {% endif %}
</div>
{% endif %}
<div class="navigation">
{{ navlink(prev, 'prev', 'Forrige') }}
{{ navlink(random, 'random', 'Tilfeldig') }}
{{ navlink(next, 'next', 'Neste') }}
</div>
<p><a id="question-error" href="{{ url_for('admin.question', question_id=question.id) }}">Funnet en feil? Rediger spørsmålet</a></p>
</div>
<div class="stats-container">
    <div class="stats">
        <div class="grade">{{ grade(stats.points, stats.total ) }}</div>
        <div class="points">
            Poeng: {{ stats.points }}/{{ stats.total }}
            {% if stats.points == 4 and stats.total == 20 %}
            <blaze>blaze it</blaze>
            {% endif %}
            ({{ percentage(stats.points, stats.total) }}%)
        </div>
        <div class="combo">Combo: {{ stats.combo }}{% for _ in range(stats.combo // 10) %}<i class="fa fa-trophy"></i>{% endfor %}</div>
        <div class="progress">Spørsmål: {{ stats.total }}/{{ stats.max }}</div>
        <div class="reset"><a href="{{ reset_url }}"><i class="fa fa-undo"></i> Nullstill poeng</a></div>
    </div>
</div>
<script type="scoop" id="question_template">
<h3>Spørsmål #{$ id }</h3>
{? if question.image }
<div class="image">
    <img src="{_ question.image }">
</div>
{?}
<h4>{$ question.text }</h4>
<form method="post">
    {? if question.multiple }
    {+ alternative in question.alternatives }
    <div class="checkbox">
        <label>
            <input type="{? if exam.multiple_correct }checkbox{? else }radio{?}" name="answer" value="{$ alternative.id }">
            {$ alternative.text }
        </label>
    </div>
    {+}
    {? else }
        {+ boolAlt in boolAlts }
        <div class="radio">
            <label>
                <input type="radio" name="answer" value="{_ boolAlt.value }">
                {$ boolAlt.label }
            </label>
        </div>
        {+}
    {?}
    <button type="submit">Svar</button>
</form>
</script>
<script type="scoop" id="stats_template">
<div class="grade">{$ stats.grade }</div>
<div class="points">
    Poeng: {$ stats.points }/{$ stats.total }
    {? if stats.points == 4 && stats.total == 20 }
    <blaze>blaze it</blaze>
    {?}
    ({$ stats.percentage }%)
</div>
<div class="combo">Combo: {$ stats.combo }{+ _ in new Array(Math.floor(stats.combo / 10)) }<i class="fa fa-trophy"></i>{+}</div>
<div class="progress">Spørsmål: {$ stats.total }/{$ stats.max }</div>
<div class="reset"><a href="{{ reset_url }}"><i class="fa fa-undo"></i> Nullstill poeng</a></div>
</script>
{% endblock %}

{% block js %}
{{ super () }}
<script>
    var q = new Questions();
</script>
{% endblock %}

memorizer/templates/quiz/quiz.html
{% extends "base.html" %}

{% block menu %}
<li class="active"><a href="{{ url_for('quiz.main') }}"><i class="fa fa-list fa-fw"></i>&nbsp; Emner</a></li>
<ul>
{% for course in courses %}
    <li>
        <a href="{{ url_for('quiz.course', course=course.code) }}">
            <i class="fa fa-book fa-fw"></i>&nbsp; {{ course.code }}
        </a>
    </li>
{% endfor %}
</ul>
{% endblock %}

{% block js %}
{{ super() }}
    {% assets "app_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}

memorizer/templates/quiz/register.html
{% from "admin/_formhelpers.html" import render_form %}
{% extends "admin/admin.html" %}

{% block content %}
<h1>Brukerregistrering</h1>

{{ render_form(form, submit_text="Registrer deg") }}
{% endblock %}

memorizer/templates/quiz/tips.html
{% extends "quiz/quiz.html" %}
{% block content %}
<h1>Tips</h1>
<h4>Hurtigtaster</h4>
<ul>
    <li>Velg alternativ: 1, 2, 3 osv.</li>
    <li>Svar: mellomrom eller q</li>
    <li>Neste/Forrige spørsmål: pil høyre/venstre eller a/d</li>
    <li>Tilfeldig spørsmål: r</li>
</ul>
{% endblock %}